export const REQUEST_BUILDER_ERROR_CODES = {
    INVALID_BASE_URL: 'INVALID_BASE_URL',
    INVALID_BEARER_TOKEN: 'INVALID_BEARER_TOKEN',
    INVALID_BODY: 'INVALID_BODY',
    INVALID_CONFIG: 'INVALID_CONFIG',
    INVALID_EXECUTOR: 'INVALID_EXECUTOR',
    INVALID_HEADER: 'INVALID_HEADER',
    INVALID_HEADERS: 'INVALID_HEADERS',
    INVALID_METHOD: 'INVALID_METHOD',
    INVALID_PARAM: 'INVALID_PARAM',
    INVALID_PARAMS: 'INVALID_PARAMS',
    INVALID_RESPONSE_TYPE: 'INVALID_RESPONSE_TYPE',
    INVALID_SIGNAL: 'INVALID_SIGNAL',
    INVALID_TIMEOUT: 'INVALID_TIMEOUT',
    INVALID_URL: 'INVALID_URL'
} as const;
